package io.noeriva.control.nat;

import io.noeriva.control.*;
import io.noeriva.control.SecurityConfiguration.Operator;
import io.r2dbc.spi.Row;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.reactive.TransactionalOperator;
import reactor.core.publisher.*;
import tools.jackson.databind.json.JsonMapper;
import static io.noeriva.control.nat.NatModels.*;

@Repository public class NatSourceStore {
 private final DatabaseClient db;private final TransactionalOperator tx;private final JsonMapper json;private final Clock clock;
 @Autowired public NatSourceStore(ObjectProvider<DatabaseClient> db,ObjectProvider<TransactionalOperator> tx,JsonMapper json){this(db.getIfAvailable(),tx.getIfAvailable(),json,Clock.systemUTC());}
 public NatSourceStore(DatabaseClient db,TransactionalOperator tx,JsonMapper json,Clock clock){this.db=db;this.tx=tx;this.json=json;this.clock=clock;}
 private DatabaseClient database(){if(db==null)throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"NAT_STORAGE_REQUIRED","NAT审计需要连接数据库");return db;}
 static void readRole(Operator actor){if(actor==null||actor.roles().stream().noneMatch(Set.of("ADMIN","OPERATOR","VIEWER")::contains))throw new ApiException(HttpStatus.FORBIDDEN,"NAT_READ_FORBIDDEN","无权读取NAT审计");}
 private static void writeRole(Operator actor){if(actor==null||!actor.roles().contains("ADMIN"))throw new ApiException(HttpStatus.FORBIDDEN,"NAT_ADMIN_REQUIRED","仅管理员可配置NAT接收来源");}
 public Mono<Void> requireDevice(String org,String id){return database().sql("SELECT id FROM device WHERE organization_id=:o AND id=:d").bind("o",org).bind("d",id).map((r,m)->r.get("id",String.class)).one().switchIfEmpty(Mono.error(ApiException.missing())).then();}
 public Mono<SourceItems> list(Operator actor){readRole(actor);if(db==null)return Mono.just(new SourceItems(List.of()));return query(" WHERE n.organization_id=:o ORDER BY n.device_id LIMIT 257").bind("o",actor.organizationId()).map((r,m)->decode(r)).all().collectList().map(items->{if(items.size()>256)throw new ApiException(HttpStatus.TOO_MANY_REQUESTS,"NAT_SOURCE_LIMIT","NAT来源数量超出上限");return new SourceItems(List.copyOf(items));});}
 public Mono<SourceView> get(String org,String device){return query(" WHERE n.organization_id=:o AND n.device_id=:d").bind("o",org).bind("d",device).map((r,m)->decode(r)).one().switchIfEmpty(Mono.error(ApiException.missing()));}
 private DatabaseClient.GenericExecuteSpec query(String where){return database().sql("SELECT /*+ MAX_EXECUTION_TIME(3000) */ n.*,d.name device_name,d.site_id FROM nat_audit_source n JOIN device d ON d.organization_id=n.organization_id AND d.id=n.device_id"+where);}
 public Mono<SourceView> save(Operator actor,String device,SettingsInput input){writeRole(actor);if(input.revision()<0)throw new IllegalArgumentException("Invalid revision");
  return database().sql("SELECT management_address FROM device WHERE organization_id=:o AND id=:d").bind("o",actor.organizationId()).bind("d",device).map((r,m)->r.get("management_address",String.class)).one().switchIfEmpty(Mono.error(ApiException.missing())).flatMap(management->{String source=ipv4(input.sourceAddress()==null||input.sourceAddress().isBlank()?management:input.sourceAddress(),true);
   String sql=input.revision()==0?"INSERT INTO nat_audit_source(organization_id,device_id,source_address,revision,enabled,quality_flags) VALUES(:o,:d,:s,1,:e,:flags)":"UPDATE nat_audit_source SET last_packet_at=IF(source_address=:s,last_packet_at,NULL),last_event_at=IF(source_address=:s,last_event_at,NULL),last_error=IF(source_address=:s,last_error,NULL),source_address=:s,revision=revision+1,enabled=:e,updated_at=UTC_TIMESTAMP(6) WHERE organization_id=:o AND device_id=:d AND revision=:r";
   var q=database().sql(sql).bind("o",actor.organizationId()).bind("d",device).bind("s",source).bind("e",input.enabled());if(input.revision()==0)q=q.bind("flags",json.writeValueAsString(BASE_FLAGS));else q=q.bind("r",input.revision());
   return q.fetch().rowsUpdated().flatMap(n->n==1?audit(actor,"NAT_SOURCE_CONFIGURED",device):Mono.error(ApiException.conflict())).then(get(actor.organizationId(),device)).as(tx::transactional);
  }).onErrorMap(org.springframework.dao.DuplicateKeyException.class,e->new ApiException(HttpStatus.CONFLICT,"NAT_SOURCE_CONFLICT","来源地址已绑定或配置版本已改变"));
 }
 public Mono<SourceView> state(Operator actor,String device,StateInput input){writeRole(actor);if(input.revision()<1)throw new IllegalArgumentException("Invalid revision");return requireDevice(actor.organizationId(),device).then(database().sql("UPDATE nat_audit_source SET enabled=:e,revision=revision+1,updated_at=UTC_TIMESTAMP(6) WHERE organization_id=:o AND device_id=:d AND revision=:r").bind("e",input.enabled()).bind("o",actor.organizationId()).bind("d",device).bind("r",input.revision()).fetch().rowsUpdated().flatMap(n->n==1?audit(actor,input.enabled()?"NAT_SOURCE_ENABLED":"NAT_SOURCE_DISABLED",device):Mono.error(ApiException.conflict())).then(get(actor.organizationId(),device))).as(tx::transactional);}
 private Mono<Void> audit(Operator a,String action,String device){return database().sql("INSERT INTO control_audit(id,organization_id,actor,action,resource_id) VALUES(:id,:o,:actor,:action,:d)").bind("id",UUID.randomUUID().toString()).bind("o",a.organizationId()).bind("actor",a.username()).bind("action",action).bind("d",device).fetch().rowsUpdated().then();}
 public Mono<List<Binding>> bindings(){return database().sql("SELECT /*+ MAX_EXECUTION_TIME(3000) */ n.organization_id,n.device_id,d.site_id,n.source_address,n.revision FROM nat_audit_source n JOIN device d ON d.organization_id=n.organization_id AND d.id=n.device_id WHERE n.enabled=1 ORDER BY n.organization_id,n.device_id LIMIT 257").map((r,m)->new Binding(r.get("organization_id",String.class),r.get("device_id",String.class),r.get("site_id",String.class),r.get("source_address",String.class),r.get("revision",Long.class))).all().collectList().map(v->{if(v.size()>256)throw new IllegalStateException("NAT_SOURCE_LIMIT");return List.copyOf(v);});}
 public record Delta(long templates,long received,long accepted,long dropped,long sequenceGaps,long unknownTemplates,long parseErrors,long duplicatePackets,long restartCount,Instant lastPacketAt,Instant lastEventAt,String error,List<String> flags){}
 public Mono<Void> record(Binding binding,Delta s){var q=database().sql("UPDATE nat_audit_source SET templates=templates+:t,received=received+:r,accepted=accepted+:a,dropped=dropped+:d,sequence_gaps=sequence_gaps+:g,unknown_templates=unknown_templates+:u,parse_errors=parse_errors+:p,duplicate_packets=duplicate_packets+:dup,restart_count=restart_count+:restart"+(s.lastPacketAt()==null?"":",last_packet_at=GREATEST(COALESCE(last_packet_at,:packet),:packet)")+(s.lastEventAt()==null?"":",last_event_at=GREATEST(COALESCE(last_event_at,:event),:event)")+",last_error=:error,quality_flags=:flags,updated_at=UTC_TIMESTAMP(6) WHERE organization_id=:org AND device_id=:device AND source_address=:source")
  .bind("t",s.templates()).bind("r",s.received()).bind("a",s.accepted()).bind("d",s.dropped()).bind("g",s.sequenceGaps()).bind("u",s.unknownTemplates()).bind("p",s.parseErrors()).bind("dup",s.duplicatePackets()).bind("restart",s.restartCount()).bind("error",Objects.toString(s.error(),"")).bind("flags",json.writeValueAsString(withBase(s.flags()))).bind("org",binding.organizationId()).bind("device",binding.deviceId()).bind("source",binding.sourceAddress());if(s.lastPacketAt()!=null)q=q.bind("packet",local(s.lastPacketAt()));if(s.lastEventAt()!=null)q=q.bind("event",local(s.lastEventAt()));return q.fetch().rowsUpdated().then();}
 public Mono<Void> persisted(String org,String device,int count){return database().sql("UPDATE nat_audit_source SET persisted=persisted+:n,last_persisted_at=UTC_TIMESTAMP(6) WHERE organization_id=:o AND device_id=:d").bind("n",count).bind("o",org).bind("d",device).fetch().rowsUpdated().then();}
 private SourceView decode(Row r){boolean enabled=Boolean.TRUE.equals(r.get("enabled",Boolean.class));Instant packet=instant(r,"last_packet_at"),event=instant(r,"last_event_at");if(Instant.EPOCH.equals(packet))packet=null;if(Instant.EPOCH.equals(event))event=null;String error=r.get("last_error",String.class);if(error!=null&&error.isBlank())error=null;List<String> flags=Arrays.asList(json.readValue(r.get("quality_flags",String.class),String[].class));String status=!enabled?"DISABLED":packet==null?"WAITING":packet.plusSeconds(120).isBefore(clock.instant())?"STALE":error!=null?"DEGRADED":"RECEIVING";
  return new SourceView(r.get("device_id",String.class),r.get("device_name",String.class),r.get("site_id",String.class),r.get("source_address",String.class),r.get("revision",Long.class),enabled,status,packet,event,instant(r,"last_persisted_at"),error,n(r,"templates"),n(r,"received"),n(r,"accepted"),n(r,"persisted"),n(r,"dropped"),n(r,"sequence_gaps"),n(r,"unknown_templates"),n(r,"parse_errors"),n(r,"duplicate_packets"),n(r,"restart_count"),instant(r,"updated_at"),withBase(flags));}
 private static List<String> withBase(List<String> flags){var merged=new LinkedHashSet<>(BASE_FLAGS);merged.addAll(flags);return List.copyOf(merged);}
 private static long n(Row r,String c){return r.get(c,Long.class);}private static LocalDateTime local(Instant i){return LocalDateTime.ofInstant(i,ZoneOffset.UTC);}private static Instant instant(Row r,String c){LocalDateTime t=r.get(c,LocalDateTime.class);return t==null?null:t.toInstant(ZoneOffset.UTC);}
 static String ipv4(String value,boolean unicast){if(value==null||!value.matches("(?:0|[1-9][0-9]{0,2})(?:\\.(?:0|[1-9][0-9]{0,2})){3}"))throw new IllegalArgumentException("必须使用规范IPv4字面地址");String[] p=value.split("\\.");int[] n=Arrays.stream(p).mapToInt(Integer::parseInt).toArray();for(int x:n)if(x>255)throw new IllegalArgumentException("IPv4范围无效");if(unicast&&(n[0]==0||n[0]==127||n[0]>=224||n[0]==169&&n[1]==254))throw new IllegalArgumentException("来源必须为单播IPv4地址");return value;}
}
