{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "noeriva.serviceAccountName" . }}
  labels:
    {{- include "noeriva.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
