#!/usr/bin/env python3
"""Generate the checked-in OpenAPI description of the implemented control/query/workbench APIs."""
import json
from pathlib import Path
S=lambda **kw: {'type':'string',**kw}
N=lambda **kw: {'type':'number',**kw}
I=lambda **kw: {'type':'integer',**kw}
R=lambda name: {'$ref':'#/components/schemas/'+name}
A=lambda item: {'type':'array','items':item}
O=lambda props,required=None: {'type':'object','properties':props,'required':list(props) if required is None else required}
T=S(format='date-time')
NULL_T={'type':['string','null'],'format':'date-time'}
NULL_S={'type':['string','null']}
NULL_N={'type':['number','null']}
B={'type':'boolean'}
METRICS=['cpu_percent','memory_percent','temperature_celsius','power_watts','bandwidth_rx_bps','bandwidth_tx_bps']
SOURCES=['primary','host','bmc','network','system','ssh']
HEALTH=['HEALTHY','WARNING','CRITICAL','UNKNOWN']
MODE=S(enum=['DEMO','CONNECTED'])
FRESHNESS=S(enum=['FRESH','STALE','MISSING'])
COVERAGE=N(minimum=0,maximum=1)
REVISION=I(format='int64',minimum=0)
SCOPED_ID=S(minLength=1,maxLength=64,pattern='^[A-Za-z0-9_.:@-]{1,64}$')
METRIC_VALUES={'type':'object','properties':{name:N() for name in METRICS},'additionalProperties':False,'maxProperties':16,'description':'Only named, finite numeric values. Omit unavailable measurements; null is rejected.'}
schemas={
 'Error':O({'code':S(),'message':S(),'requestId':S()}),
 'Session':O({'username':S(),'organizationId':S(),'roles':A(S()),'mode':MODE,'timezone':NULL_S,'accessToken':S(pattern='^[A-Za-z0-9_-]{43}$',description='Opaque 256-bit bearer handle, valid for one hour after issue. Not a JWT. A Bearer-authenticated session read returns the existing token without extending its lifetime.'),'tokenType':S(enum=['Bearer'])}),
 'Overview':O({**{name:I(format='int64',minimum=0) for name in ['devices','critical','warning','healthy','unknown','stale','activeAlerts','collectors']},'asOf':T,'mode':MODE}),
 'Site':O({'id':S(),'name':S(),'timezone':NULL_S}),
 'Device':O({'id':S(),'name':S(),'type':S(enum=['HOST','BMC','ROUTER','SWITCH','FIREWALL']),'siteId':S(),'siteName':S(),'vendor':NULL_S,'model':NULL_S,'managementAddress':S(),'health':S(enum=['HEALTHY','WARNING','CRITICAL','UNKNOWN']),'availability':S(enum=['ONLINE','OFFLINE','UNKNOWN']),'lastSeen':NULL_T,'revision':I(),'capabilities':A(S())}),
 'CreateDevice':O({'name':S(minLength=1,maxLength=120,pattern=r'\S'),'type':S(enum=['HOST','BMC','ROUTER','SWITCH','FIREWALL']),'siteId':S(minLength=1,maxLength=64,pattern=r'\S'),'vendor':{**NULL_S,'maxLength':120},'model':{**NULL_S,'maxLength':120},'managementAddress':S(minLength=1,maxLength=253,pattern='^[a-zA-Z0-9.:_-]{1,253}$',description='Inventory address identifier; validation checks this character pattern, not DNS resolution or strict IP syntax.')},['name','type','siteId','managementAddress']),
 'Interface':O({'id':S(),'deviceId':S(),'name':S(),'macAddress':NULL_S,'speedBps':S(pattern='^[0-9]{1,20}$',description='Unsigned decimal string, at most 18446744073709551615; preserves UInt64 precision.'),'adminStatus':S(),'operStatus':S()}),
 'RegisterInterface':O({'name':S(minLength=1,maxLength=120,pattern=r'\S'),'speedBps':S(pattern='^[0-9]{1,20}$',description='Unsigned decimal string; numeric value must not exceed 18446744073709551615.'),'macAddress':{**NULL_S,'maxLength':40}},['name','speedBps']),
 'SourceState':O({'sourceId':S(enum=SOURCES),'kind':S(enum=['DeviceSummaryObserved','SourceHealthChanged']),'observedAt':T,'sequence':I(format='int64',minimum=0,maximum=9223372036854775806),'epoch':S(),'health':S(enum=HEALTH),'metrics':METRIC_VALUES,'freshness':FRESHNESS}),
 'Summary':O({'device':R('Device'),'sources':A(R('SourceState')),'activeAlerts':I(),'asOf':T,'sourceFreshness':FRESHNESS,'coverage':COVERAGE,'resolution':I(enum=[0]),'dataRevision':S(description='Decimal device revision. This summary DTO uses a string; query response revisions are JSON integers.'),'provisional':B,'qualityFlags':A(S())}),
 'MetricResponse':O({'deviceId':S(),'metric':S(enum=METRICS),'unit':S(),'from':T,'to':T,'asOf':NULL_T,'source':S(),'sourceFreshness':FRESHNESS,'resolution':I(minimum=1,description='Query step in seconds.'),'dataRevision':REVISION,'provisional':B,'coverage':COVERAGE,'qualityFlags':A(S()),'points':{'type':'array','maxItems':2000,'items':O({'timestamp':T,'value':NULL_N})}}),
 'HeatmapCell':O({'date':S(format='date'),'hour':I(minimum=0,maximum=23),'state':S(enum=['OBSERVED','OBSERVED_ZERO','MISSING','PARTIAL','FUTURE','DST_MISSING']),'value':NULL_N,'unit':S(enum=['bps']),'aggregation':S(),'intervals':A(O({'from':T,'to':T,'durationSeconds':I(format='int64',minimum=0)})),'coverage':COVERAGE,'asOf':NULL_T,'sourceFreshness':FRESHNESS,'dataRevision':REVISION,'provisional':B,'qualityFlags':A(S())}),
 'Heatmap':O({'deviceId':S(),'interfaceId':S(),'timezone':S(),'direction':S(enum=['rx','tx']),'statistic':S(enum=['time_weighted_mean']),'unit':S(enum=['bps']),'fromDate':S(format='date'),'toDate':S(format='date'),'asOf':NULL_T,'source':S(),'sourceFreshness':FRESHNESS,'dataRevision':REVISION,'coverage':COVERAGE,'resolution':I(enum=[300],description='Stored UTC rollup resolution in seconds; presentation cells are local hours.'),'provisional':B,'qualityFlags':A(S()),'cells':{'type':'array','items':R('HeatmapCell'),'minItems':168,'maxItems':168}}),
 'Alert':O({'id':S(),'deviceId':S(),'deviceName':S(),'severity':S(),'state':S(enum=['OPEN','ACKNOWLEDGED','RESOLVED']),'title':S(),'openedAt':T,'acknowledgedAt':NULL_T,'acknowledgedBy':NULL_S,'revision':I()}),
 'Event':O({'id':S(),'deviceId':S(),'kind':S(),'severity':S(),'message':NULL_S,'observedAt':T,'ingestedAt':T,'source':S(),'qualityFlags':A(S())}),
 'Collector':O({'id':S(),'name':S(),'siteId':NULL_S,'status':S(),'lastHeartbeat':NULL_T,'lastSuccessfulCollection':NULL_T,'queueBytes':I(format='int64'),'queueLimitBytes':I(format='int64'),'oldestQueuedAt':NULL_T,'version':S(),'capabilities':A(S()),'source':S()}),
 'TopologyEvidence':O({'protocol':S(),'sourceDeviceId':S(),'sourceInterface':NULL_S,'sourceRef':NULL_S,'observedAt':T,'detail':S()}),
 'Node':O({'id':S(),'name':S(),'type':S(),'health':S(enum=HEALTH),'registered':B,'siteId':NULL_S,'availability':S(enum=['ONLINE','OFFLINE','UNKNOWN']),'freshness':FRESHNESS,'vlanIds':A(I(minimum=1,maximum=4094)),'addresses':A(S()),'mac':NULL_S,'confidence':S(enum=['OBSERVED','CORROBORATED','UNCONFIRMED','CONFLICT']),'qualityFlags':A(S()),'evidence':{**A(R('TopologyEvidence')),'maxItems':8}}),
 'Edge':O({'id':S(),'source':S(),'target':S(),'sourceInterface':NULL_S,'targetInterface':NULL_S,'kind':S(description='PHYSICAL for LLDP/CDP adjacency; L2_INFERRED for bounded FDB/DHCP attachment evidence; L3_INFERRED for ARP. Legacy explicitly stored graph kinds may also occur in ALL.'),'provenance':S(),'observedAt':T,'inferred':B,'confidence':S(enum=['OBSERVED','CORROBORATED','UNCONFIRMED','CONFLICT']),'vlanIds':A(I(minimum=1,maximum=4094)),'qualityFlags':A(S()),'evidence':{**A(R('TopologyEvidence')),'maxItems':8}}),
 'TopologyVlan':O({'vlanId':I(minimum=1,maximum=4094),'name':S(),'nodeCount':I(minimum=0),'edgeCount':I(minimum=0)}),
 'Topology':O({'nodes':{'type':'array','items':R('Node'),'maxItems':200},'edges':{'type':'array','items':R('Edge'),'maxItems':400},'asOf':T,'qualityFlags':A(S()),'view':S(enum=['PHYSICAL','ALL']),'vlans':A(R('TopologyVlan'))}),
 'Capability':O({'id':S(),'name':S(),'roadmapTier':S(enum=['MVP','PLANNED']),'maturity':S(enum=['EXPERIMENTAL','DESIGNED']),'coverage':S(enum=['PARTIAL','NONE']),'verification':S(enum=['INTEGRATION_TESTED','FIXTURE_TESTED','NOT_TESTED']),'phase':I(minimum=1,maximum=14),'notes':S()}),
 'Capabilities':O({'items':A(R('Capability')),'mode':MODE}),
 'Observation':O({'id':S(pattern='^[a-zA-Z0-9_-]{1,128}$'),'deviceId':S(minLength=1,maxLength=64,pattern=r'\S'),'sourceId':S(enum=SOURCES),'kind':S(enum=['DeviceSummaryObserved','SourceHealthChanged']),'epoch':S(minLength=1,maxLength=64,pattern=r'\S'),'sequence':I(format='int64',minimum=0,maximum=9223372036854775806),'observedAt':{**T,'description':'Source observation time, at least 2000-01-01T00:00:00Z and no more than 120 seconds ahead of server time.'},'health':S(enum=HEALTH),'metrics':METRIC_VALUES,'message':{**NULL_S,'maxLength':1000}},['id','deviceId','sourceId','kind','epoch','sequence','observedAt','health','metrics']),
 'RepairRequest':{**O({'deviceId':SCOPED_ID,'interfaceId':SCOPED_ID,'from':T,'to':T,'direction':S(enum=['rx','tx'])}),'description':'One owned interface. Positive window of at most one day, both boundaries whole-second UTC five-minute boundaries, to no later than now. Source is read from the authorized interface catalog source_id and persisted with the job; it is not a request field.'},
 'RepairJob':O({'id':S(format='uuid'),'type':S(enum=['ROLLUP_REPAIR']),'organizationId':S(),'createdBy':S(),'deviceId':S(),'interfaceId':S(),'sourceId':S(),'direction':S(enum=['rx','tx']),'from':T,'to':T,'status':S(enum=['PENDING','RUNNING','SUCCEEDED','FAILED']),'attempts':I(minimum=0,maximum=3),'bucketCount':{'type':['integer','null'],'minimum':1,'maximum':288},'errorCode':{**NULL_S,'enum':[None,'LEASE_EXHAUSTED','DEADLINE_EXCEEDED','QUERY_CAPACITY','RECOMPUTATION_UNAVAILABLE','PROVIDER_UNAVAILABLE','INVALID_SOURCE_DATA','REPAIR_FAILED']},'createdAt':T,'updatedAt':T}),
}
page=lambda name:O({'items':A(R(name)),'nextCursor':NULL_S,'asOf':T,'source':S(),'mode':MODE})
items=lambda name:O({'items':A(R(name)),'asOf':T})
param=lambda name,schema,required=False,where='query':{'name':name,'in':where,'required':required,'schema':schema}
paths={}
def endpoint(path,method,summary,response=None,parameters=(),body=None,status='200',description=None,roles=None):
 op={'summary':summary,'x-required-roles':roles or (['ADMIN','OPERATOR'] if method=='post' else ['ADMIN','OPERATOR','VIEWER']),'parameters':list(parameters),'responses':{status:{'description':'Success',**({'content':{'application/json':{'schema':response}}} if response else {})},'400':{'description':'Invalid bounded request'},'401':{'description':'Authentication required; security-filter errors may have an empty body'},'403':{'description':'Role or request-header denied; security-filter errors may have an empty body'},'404':{'description':'Not found in authorized scope'},'409':{'description':'Revision conflict or unsupported source'},'429':{'description':'Capacity reached; Retry-After applies','headers':{'Retry-After':{'schema':S(),'description':'Application error responses use 1 second.'}}},'500':{'description':'Internal request failure; no provider details disclosed'},'503':{'description':'Provider or feature unavailable; not an empty or zero result'}}}
 if description:op['description']=description
 for code,error in op['responses'].items():
  error.setdefault('headers',{}).update({'X-Request-Id':{'schema':S(format='uuid')},'Cache-Control':{'schema':S(enum=['no-store'])}})
  if code in ('400','404','409','429','500','503'):error['content']={'application/json':{'schema':R('Error')}}
 for name in ('id','interfaceId'):
  if '{'+name+'}' in path:op['parameters'].append(param(name,S(),True,'path'))
 if body is not None:
  op['requestBody']={'required':True,'content':{'application/json':{'schema':body}}}
 if method in ('post','put','patch','delete'):
  op['parameters'].append(param('X-Noeriva-Request',S(enum=['1']),True,'header'))
 paths.setdefault(path,{})[method]=op
endpoint('/session','get','Get session and exchange Basic credentials for an opaque bearer token',R('Session'),description='Basic authentication issues a one-hour token. Bearer authentication returns the existing token without renewal. Current account roles are read again on every authenticated request. timezone is currently null; the client must choose an explicit heatmap timezone.')
endpoint('/overview','get','Current control-plane counts; stale overlaps health counts',R('Overview'))
endpoint('/sites','get','Authorized sites',items('Site'))
endpoint('/devices','get','Keyset page from inventory/current checkpoints',page('Device'),[param('limit',I(minimum=1,maximum=100,default=50)),param('cursor',S(maxLength=64,default='')),param('q',S(maxLength=120,default='')),param('siteId',S(maxLength=64,default='')),param('type',S(maxLength=32,default='')),param('health',S(maxLength=16,default=''))],description='Stable device ID ascending order. Use the returned nextCursor unchanged and reset it when filters change.')
endpoint('/devices','post','Create UNKNOWN inventory asset with transactional outbox',R('Device'),body=R('CreateDevice'),status='201')
endpoint('/devices/{id}','get','Authorized device',R('Device'))
endpoint('/devices/{id}/summary','get','Independent source freshness/current state',R('Summary'))
endpoint('/devices/{id}/interfaces','get','Interfaces owned by device',items('Interface'))
endpoint('/devices/{id}/interfaces','post','Register interface metadata; no real-device operation',R('Interface'),body=R('RegisterInterface'),status='201')
endpoint('/devices/{id}/metrics','get','Named bounded VM metric query',R('MetricResponse'),[param('metric',S(enum=METRICS,default='cpu_percent')),param('from',T),param('to',T),param('points',I(minimum=2,maximum=2000,default=120))],description='Positive range at most seven days; to allows at most five seconds of server clock skew. Defaults: to=now, from=to minus one hour. points is a maximum budget, not a promise of zero-filled samples. Requires an assigned metric capability; unsupported sources return 409.')
endpoint('/devices/{id}/interfaces/{interfaceId}/bandwidth/heatmap','get','Seven local dates, 168 cells from revisioned summaries',R('Heatmap'),[param('timezone',S(description='Explicit Java ZoneId; use an IANA name such as Asia/Shanghai or America/New_York.'),True),param('direction',S(enum=['rx','tx'],default='rx')),param('days',I(enum=[7],default=7)),param('statistic',S(enum=['time_weighted_mean'],default='time_weighted_mean'))],description='Current local date and six preceding dates. Local-hour cells retain UTC intervals, including repeated and missing DST hours. Missing values stay null. Organization/device/interface ownership is checked before providers are queried. The data source is resolved from that authorized interface catalog source_id (manual primary or SNMP network), not supplied by the requester.')
for path in ['/events','/devices/{id}/activity']:
 endpoint(path,'get','Bounded typed history; provider failure is explicit',page('Event'),[param('deviceId',S(default='')),param('from',T),param('to',T),param('cursor',S(maxLength=512,default='')),param('limit',I(minimum=1,maximum=100,default=50))],description='Positive range at most 31 days. Defaults: to=now, from=to minus seven days. Opaque event keyset cursor. A device ID in the path takes precedence over the deviceId query parameter.')
endpoint('/alerts','get','Alert lifecycle',items('Alert'),[param('deviceId',S()),param('state',S()),param('limit',I(minimum=1,maximum=100,default=50))])
endpoint('/alerts/{id}/acknowledge','post','Optimistic acknowledge; never resolves the problem',R('Alert'),body=O({'revision':I(minimum=1)}))
for path in ['/topology']:endpoint(path,'get','Bounded evidence-based physical and inferred topology',R('Topology'),parameters=[param('deviceId',S(default='',maxLength=64)),param('siteId',S(default='',maxLength=64)),param('view',S(enum=['PHYSICAL','ALL'],default='PHYSICAL')),param('vlanId',I(minimum=1,maximum=4094)),param('limit',I(minimum=1,maximum=200,default=200))],description='Read-only snapshot: at most 200 nodes/400 edges, 512 inventory candidates, 128 enabled preferred sources, 256 KiB/source, 512 rows/table, 16384 endpoint facts and 4096 derived endpoints. Two concurrent queries/process, SQL 3s and overall 8s budgets. Source evidence must be <=180s old; never implicitly falls back from SNMP to SSH. PHYSICAL excludes inferred and legacy logical edges; ALL includes separately typed L2 and L3 inferences. UI requests ALL, showing physical and L2 by default with L3 opt-in. Unregistered evidence nodes are not CMDB writes, availability remains UNKNOWN. Missing mappings, shared VLAN FDBs, duplicate identities, uplink learning and limits are explicit quality flags. A requested device is authorized before reading; site and VLAN filters are applied before output limits. VLAN counts contain only returned snapshot nodes/edges, never organization-wide totals. Empty VLAN arrays mean unknown membership, not VLAN 0. Offline registered assets retain inventory health/availability even if ARP is freshly cached. No arbitrary subnet or ambiguous identity becomes a physical link.')
endpoint('/collectors','get','Collection source inventory and visible provenance',items('Collector'))
endpoint('/capabilities','get','Compact current capability status',R('Capabilities'),description='Eleven current domain summaries: inventory, workspace, metrics, alerts, incidents, configuration, checks, nat, evidence, network, governance. Maturity, coverage and verification are reported independently; FIXTURE_TESTED and INTEGRATION_TESTED do not imply DEVICE_VERIFIED. Typed imported evidence and collector-reported workflows are partial implementations; the separate device-support catalog describes new read-only protocol drivers; signatures and WORM remain unimplemented. Consult docs/capabilities/capability-matrix.json for the full V5 roadmap. Automated synthetic verification does not establish real-device support.')
endpoint('/ingest/batches','post','COLLECTOR only; accepted after Kafka acks=all',O({'batchId':S(),'status':S(enum=['SIMULATED','DURABLY_QUEUED']),'accepted':I(minimum=1,maximum=500),'receivedAt':T}),body=O({'batchId':S(pattern='^[a-zA-Z0-9_-]{1,128}$'),'events':{'type':'array','items':R('Observation'),'minItems':1,'maxItems':500}}),status='202',roles=['COLLECTOR'],description='Low-volume source state observations only. Validate batch scope before publication. Success means all records acknowledged; a failed publication may have durably queued a subset, so retries must preserve event IDs, epoch and sequence. This is not atomic batch ingestion. Demo returns SIMULATED without a durability claim.')
endpoint('/query-jobs','post','ADMIN: queue one UTC-aligned <=1day rollup repair',R('RepairJob'),body=R('RepairRequest'),status='202',roles=['ADMIN'],description='Durable PENDING job plus audit entry after organization and interface ownership checks. At most 100 active jobs per organization. Demo returns 503 REPAIR_JOBS_UNAVAILABLE. Production processing requires NOERIVA_ROLLUP_ENABLED=true; a disabled worker can leave accepted jobs PENDING. Source is resolved from the authorized interface catalog source_id (manual primary or SNMP network), never from the request. The sourceId is persisted with the job and reused for execution and lease retries, independent of the global rollup default. Each claimed job has a 30-second deadline and two-minute lease, with at most three claims after lease expiry. Missing raw data fails explicitly; this endpoint does not export data.')
endpoint('/query-jobs/{id}','get','Durable repair job in authorized organization',R('RepairJob'),description='Organization-scoped job lookup. Demo returns 503 REPAIR_JOBS_UNAVAILABLE. bucketCount is populated on success; errorCode on failure; otherwise those fields are null.')
endpoint('/stream/device-status','get','Bounded authenticated snapshot-required SSE hints',description='text/event-stream with event: snapshot-required and JSON data {revision,asOf}, emitted initially and every 15 seconds. revision is a connection-local integer counter, not a durable data revision or replay cursor. At most 200 connections per process; disconnect/cancellation releases the permit. Slow-client hints may be dropped. Fetch a fresh snapshot after reconnect.')
paths['/stream/device-status']['get']['responses']['200']['content']={'text/event-stream':{'schema':S()}}
from workbench_openapi import extend
extend(schemas, endpoint, globals())
from device_access_openapi import extend as extend_device_access
extend_device_access(schemas, endpoint, globals())
from discovery_openapi import extend as extend_discovery
extend_discovery(schemas, endpoint, globals())
from traffic_openapi import extend as extend_traffic
extend_traffic(schemas, endpoint, globals())
from settings_openapi import extend as extend_settings
extend_settings(schemas, endpoint, globals())
from alerts_openapi import extend as extend_alerts
extend_alerts(schemas, endpoint, globals())
result={'openapi':'3.1.0','info':{'title':'NOERIVA Clarity workspace API','version':'0.1.0','description':'Current organization is derived from authentication. Only implemented endpoints are listed. Clarity includes bounded current-state queries and typed incident, audit, configuration, evidence, collector-reported check, and temporal correlation workflows. Read-only SNMP/Redfish/fixed-profile SSH access, credential administration, periodic collection, safe device SSE and bounded review of stored neighbor evidence are included. Signatures, WORM, remote device configuration are outside this contract; hardware evidence is model/protocol-specific and does not establish whole-family certification. All mutations require X-Noeriva-Request: 1 and application/json. x-required-roles lists alternative accepted account roles. Basic and opaque Bearer authentication are supported; cookie authentication is not used. Nullable measurements are not zero. JSON integer revisions follow Java int64; clients must preserve precision when handling large values.'},'servers':[{'url':'/api/v1'}],'security':[{'bearerSession':[]},{'basicAuth':[]}],'paths':paths,'components':{'securitySchemes':{'basicAuth':{'type':'http','scheme':'basic'},'bearerSession':{'type':'http','scheme':'bearer','bearerFormat':'opaque256bit'}},'schemas':schemas}}
out=Path(__file__).resolve().parents[1]/'schemas/api/openapi.json'
out.write_text(json.dumps(result,indent=2)+'\n')
print(f'Wrote {len(paths)} API paths and {len(schemas)} schemas to {out}')
