"""Independent NBAR and NAT traffic contracts, including bounded chart summaries."""
def extend(schemas, endpoint, h):
    S,I,N,R,A,O = (h[k] for k in ['S','I','N','R','A','O'])
    T,NT,NS,NN,B,param,page = (h[k] for k in ['T','NULL_T','NULL_S','NULL_N','B','param','page'])
    nullable_int = {'type':['integer','null']}
    flags=A(S())
    schemas['ApplicationSource']=O({**{k:S() for k in ['deviceId','deviceName','siteId','status','errorCode','errorMessage','protocol']},**{k:I(format='int64') for k in ['revision','credentialRevision']},'enabled':B,'intervalSeconds':I(),'interfaceIndices':A(I()),'maxRows':I(),'lastAttemptAt':NT,'lastSuccessAt':NT,'nextPollAt':NT,'lastRowCount':I(),'qualityFlags':flags})
    schemas['ApplicationObservation']=O({**{k:S() for k in ['id','deviceId','interfaceName','application','direction','sourceEpoch']},**{k:I() for k in ['interfaceIndex','protocolIndex']},'observedAt':T,'bytes':{**NS,'pattern':'^[0-9]+$','description':'Unsigned cumulative counter decimal string; never a rate.'},'packets':{**NS,'pattern':'^[0-9]+$'},**{k:NN for k in ['reportedBps','derivedBps','derivedPacketsPerSecond','intervalSeconds']},'qualityFlags':flags})
    schemas['ApplicationSettings']=O({'revision':I(minimum=0),'enabled':B,'intervalSeconds':I(minimum=30,maximum=3600),'interfaceIndices':{'type':'array','items':I(minimum=1),'minItems':1,'maxItems':8,'uniqueItems':True},'maxRows':I(minimum=1,maximum=256)})
    schemas['TrafficState']=O({'revision':I(minimum=1),'enabled':B})
    schemas['ApplicationSummaryItem']=O({'application':S(),'direction':S(enum=['IN','OUT']),'interfaceIndices':A(I()),'derivedBps':NN,'reportedBps':NN,'observationCount':I(),'qualityFlags':flags})
    schemas['ApplicationSummary']=O({'deviceId':S(),'asOf':T,'observedAt':NT,'source':S(enum=['CLICKHOUSE']),'mode':S(enum=['CONNECTED']),'freshness':h['FRESHNESS'],'rateBasis':S(enum=['COUNTER_DELTA_PER_SECOND']),'interfaceIndices':A(I()),'sampleRows':I(),'totalApplications':I(),'truncated':B,'qualityFlags':flags,'items':A(R('ApplicationSummaryItem'))})
    filters=[param('deviceId',S(maxLength=64),True),param('interfaceIndex',I(minimum=1)),param('direction',S(enum=['IN','OUT'])),param('q',S(maxLength=80))]
    endpoint('/applications/sources','get','Independent SNMP NBAR source configurations',page('ApplicationSource'),[param('limit',I(minimum=1,maximum=200,default=50)),param('cursor',S())])
    endpoint('/applications/devices/{id}/settings','post','Save independent application collection settings',R('ApplicationSource'),body=R('ApplicationSettings'),roles=['ADMIN'],description='Reuses the owned SNMP slot credentials. maxRows is a total protocol row bound across selected interfaces and must be at least the number of interfaces. Source activation is independent of ordinary SNMP monitoring.')
    endpoint('/applications/devices/{id}/state','post','Enable or disable independent application collection',R('ApplicationSource'),body=R('TrafficState'),roles=['ADMIN'])
    endpoint('/applications/devices/{id}/collect','post','Request a bounded NBAR sample',R('ApplicationSource'),body=O({'revision':I(minimum=1)}),roles=['ADMIN'],description='At most four concurrent collectors, 45 second deadline. May collect while periodic application collection is disabled.')
    endpoint('/applications/observations','get','Newest-first application observation history',page('ApplicationObservation'),filters+[param('from',T),param('to',T),param('limit',I(minimum=1,maximum=500,default=100)),param('cursor',S())],description='At most seven days. Omitted bounds default to the latest hour and are frozen in the returned cursor. Filters and organization/device scope bind the cursor. reportedBps is the device-reported value, derivedBps is the validated counter delta divided by elapsed time; no baseline remains null.')
    endpoint('/applications/summary','get','Latest sample application rate distribution',R('ApplicationSummary'),filters+[param('limit',I(minimum=1,maximum=30,default=12))],description='Reads at most 512 rows from the newest device sample, never mixes older matching applications into that sample. Group by application and direction across selected interfaces, ordered by derivedBps descending with nulls last. All component rates must be present before a sum is returned. reportedBps remains separate. Multiple interfaces can observe the same traffic and carry INTERFACE_OVERLAP_POSSIBLE; this is not deduplicated end-to-end traffic. Quality flags preserve baseline/reset/row-limit evidence, and a stale sample remains STALE.')
    schemas['NatSource']=O({**{k:S() for k in ['deviceId','deviceName','siteId','sourceAddress','status']},**{k:I(format='int64') for k in ['revision','templates','received','accepted','persisted','dropped','sequenceGaps','unknownTemplates','parseErrors','duplicatePackets','restartCount']},'enabled':B,'lastError':NS,**{k:NT for k in ['lastPacketAt','lastEventAt','lastPersistedAt','updatedAt']},'qualityFlags':flags})
    schemas['NatEvent']=O({**{k:S() for k in ['id','deviceId','siteId','sourceAddress','exporterEpoch','templateSha256','packetSha256','eventType','provenance']},**{k:I(format='int64') for k in ['sourceDomain','packetSequence','templateId','recordIndex']},**{k:nullable_int for k in ['protocol','vrfId','privatePort','publicPort','destinationPort','translatedDestinationPort','poolId']},**{k:NS for k in ['privateIp','publicIp','destinationIp','translatedDestinationIp']},'deviceEventAt':NT,'exportedAt':T,'receivedAt':T,'qualityFlags':flags})
    schemas['NatEventPage']=O({'items':A(R('NatEvent')),'nextCursor':NS,'asOf':T,'mode':S(enum=['CONNECTED'])})
    endpoint('/nat-audit/sources','get','Independent trusted-source NAT capture state',O({'items':A(R('NatSource'))}))
    endpoint('/nat-audit/devices/{id}/settings','post','Bind a unique exporter IPv4 to the owned NAT source',R('NatSource'),body=O({'revision':I(minimum=0),'enabled':B,'sourceAddress':NS},['revision','enabled']),roles=['ADMIN'])
    endpoint('/nat-audit/devices/{id}/state','post','Enable or disable independent NAT capture',R('NatSource'),body=R('TrafficState'),roles=['ADMIN'])
    endpoint('/nat-audit/events','get','All retained NAT events, newest receipt first',R('NatEventPage'),[param('deviceId',S(maxLength=64),True),param('from',T),param('to',T),param('protocol',I(minimum=0,maximum=255)),param('privateIp',S(maxLength=45)),param('publicIp',S(maxLength=45)),param('limit',I(minimum=1,maximum=100,default=50)),param('cursor',S(maxLength=800))],description='Default all retained history: omit BOTH from and to. An explicit range requires both bounds with from < to; no fixed day cap. The first request freezes its upper cutoff, returned cursors bind organization/device/filters/range and paginate by (receivedAt,id) descending. A receipt-ordered lightweight index examines at most 128 candidates, then canonical FINAL identity lookup rejects later replays. A page can be empty while nextCursor remains non-null when candidates were replays; continue until the cursor is null. Each query has 128 MiB read/memory, two threads and four second server budgets; sparse filters that exceed them return 503, never a false empty success. UDP observations retain COMPLETENESS_NOT_GUARANTEED; no full session reconstruction is implied.')
    endpoint('/devices/{id}/bandwidth/heatmap','get','Seven local dates of device aggregate bandwidth',R('Heatmap'),[param('timezone',S(),True),param('direction',S(enum=['rx','tx'],default='rx')),param('days',I(enum=[7],default=7)),param('statistic',S(enum=['sample_mean','time_weighted_mean'],default='time_weighted_mean'))],description="Owned device's named rx/tx bandwidth gauge, sampled at at most 2000 equally spaced query points into 168 local-hour cells. No interface re-summing occurs. Response interfaceId is __device__, statistic is sample_mean and coverage is sampled-point coverage, not counter-delta duration coverage. Device aggregate includes the collector's observed interfaces; logical and physical interfaces can overlap, disclosed by INTERFACE_OVERLAP_POSSIBLE. Null remains unavailable. Original per-interface counter-rollup endpoint remains available.")
    # The same response envelope carries two explicitly distinct measurement definitions.
    schemas['Heatmap']['properties']['statistic']=S(enum=['time_weighted_mean','sample_mean'])
