package io.noeriva.control.applications;

import io.noeriva.control.*;
import io.r2dbc.spi.Row;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.http.HttpStatus;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.reactive.TransactionalOperator;
import reactor.core.publisher.*;
import tools.jackson.databind.json.JsonMapper;
import static io.noeriva.control.applications.ApplicationModels.*;

@Repository public class ApplicationStore {
    private final DatabaseClient db;private final TransactionalOperator tx;private final JsonMapper json;
    public ApplicationStore(ObjectProvider<DatabaseClient> db,ObjectProvider<TransactionalOperator> tx,JsonMapper json){this.db=db.getIfAvailable();this.tx=tx.getIfAvailable();this.json=json;}
    private DatabaseClient database(){if(db==null||tx==null)throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"CONNECTED_STORAGE_REQUIRED","Application monitoring requires connected storage");return db;}
    private static Instant at(Row r,String key){var v=r.get(key,LocalDateTime.class);return v==null?null:v.toInstant(ZoneOffset.UTC);}
    private List<Integer> indices(Row r){var value=r.get("interface_indices",String.class);return value==null?List.of():List.of(json.readValue(value,Integer[].class));}
    private List<String> flags(Row r){var value=r.get("quality_flags",String.class);return value==null?List.of():List.of(json.readValue(value,String[].class));}
    private Stored decode(Row r){String baseline=r.get("baseline",String.class);return new Stored(r.get("organization_id",String.class),r.get("device_id",String.class),r.get("revision",Long.class),Boolean.TRUE.equals(r.get("enabled",Boolean.class)),r.get("interval_seconds",Integer.class),indices(r),r.get("max_rows",Integer.class),r.get("status",String.class),at(r,"last_attempt_at"),at(r,"last_success_at"),at(r,"next_poll_at"),r.get("error_code",String.class),r.get("error_message",String.class),r.get("lease_token",String.class),baseline==null?null:json.readValue(baseline,Sample.class),r.get("baseline_credential_revision",Long.class),r.get("last_row_count",Integer.class),flags(r));}
    public Mono<Stored> get(String org,String device){return database().sql("SELECT /*+ MAX_EXECUTION_TIME(3000) */ * FROM application_source WHERE organization_id=:org AND device_id=:device").bind("org",org).bind("device",device).map((r,m)->decode(r)).one();}
    private static final String SOURCES="SELECT /*+ MAX_EXECUTION_TIME(3000) */ d.id device_id,d.name device_name,d.site_id,c.revision credential_revision,a.revision,a.enabled,a.interval_seconds,a.interface_indices,a.max_rows,a.status,a.last_attempt_at,a.last_success_at,a.next_poll_at,a.error_code,a.error_message,a.last_row_count,a.quality_flags FROM device d JOIN device_connection c ON c.organization_id=d.organization_id AND c.device_id=d.id AND c.slot='snmp' LEFT JOIN application_source a ON a.organization_id=d.organization_id AND a.device_id=d.id WHERE d.organization_id=:org";
    private Source source(Row r){Long revision=r.get("revision",Long.class);return new Source(r.get("device_id",String.class),r.get("device_name",String.class),r.get("site_id",String.class),revision==null?0:revision,Boolean.TRUE.equals(r.get("enabled",Boolean.class)),revision==null?60:r.get("interval_seconds",Integer.class),indices(r),revision==null?128:r.get("max_rows",Integer.class),revision==null?"NOT_CONFIGURED":r.get("status",String.class),at(r,"last_attempt_at"),at(r,"last_success_at"),at(r,"next_poll_at"),Objects.toString(r.get("error_code",String.class),""),Objects.toString(r.get("error_message",String.class),""),r.get("credential_revision",Long.class),"CISCO_NBAR_SNMP",revision==null?0:r.get("last_row_count",Integer.class),flags(r));}
    public Mono<Source> source(String org,String device){return database().sql(SOURCES+" AND d.id=:device").bind("org",org).bind("device",device).map((r,m)->source(r)).one().switchIfEmpty(Mono.error(ApiException.missing()));}
    public Flux<Source> sources(String org,String after,int limit){return database().sql(SOURCES+" AND d.id>:after ORDER BY d.id LIMIT :limit").bind("org",org).bind("after",after).bind("limit",limit).map((r,m)->source(r)).all();}
    public Mono<Stored> save(String org,String actor,String device,SettingsInput input){return Mono.defer(()->{
        String sql=input.revision()==0?"INSERT INTO application_source(organization_id,device_id,revision,enabled,interval_seconds,interface_indices,max_rows,status,next_poll_at,quality_flags) VALUES(:org,:device,1,:enabled,:interval,:indices,:max,:status,UTC_TIMESTAMP(6),'[]')":
            "UPDATE application_source SET revision=revision+1,enabled=:enabled,interval_seconds=:interval,interface_indices=:indices,max_rows=:max,status=:status,next_poll_at=UTC_TIMESTAMP(6),baseline=NULL,baseline_credential_revision=0,last_row_count=0,quality_flags='[]',error_code='',error_message='' WHERE organization_id=:org AND device_id=:device AND revision=:revision AND (lease_until IS NULL OR lease_until<UTC_TIMESTAMP(6))";
        var spec=database().sql(sql).bind("org",org).bind("device",device).bind("enabled",input.enabled()).bind("interval",input.intervalSeconds()).bind("indices",json.writeValueAsString(input.interfaceIndices())).bind("max",input.maxRows()).bind("status",input.enabled()?"QUEUED":"DISABLED");if(input.revision()!=0)spec=spec.bind("revision",input.revision());
        return spec.fetch().rowsUpdated().flatMap(n->n==1?audit(org,actor,"APPLICATION_SETTINGS_SAVED",device):Mono.error(ApiException.conflict())).then(get(org,device)).as(tx::transactional).onErrorMap(org.springframework.dao.DuplicateKeyException.class,e->ApiException.conflict());
    });}
    public Mono<Stored> state(String org,String actor,String device,StateInput input){return Mono.defer(()->database().sql("UPDATE application_source SET revision=revision+1,enabled=:enabled,status=:status,next_poll_at=UTC_TIMESTAMP(6),baseline=NULL,baseline_credential_revision=0 WHERE organization_id=:org AND device_id=:device AND revision=:revision AND (lease_until IS NULL OR lease_until<UTC_TIMESTAMP(6))")
        .bind("org",org).bind("device",device).bind("revision",input.revision()).bind("enabled",input.enabled()).bind("status",input.enabled()?"QUEUED":"DISABLED").fetch().rowsUpdated()
        .flatMap(n->n==1?audit(org,actor,input.enabled()?"APPLICATION_ENABLED":"APPLICATION_DISABLED",device):Mono.error(ApiException.conflict())).then(get(org,device)).as(tx::transactional));}
    public Flux<Stored> due(String org,int limit){return database().sql("SELECT /*+ MAX_EXECUTION_TIME(3000) */ * FROM application_source WHERE organization_id=:org AND enabled=1 AND next_poll_at<=UTC_TIMESTAMP(6) AND (lease_until IS NULL OR lease_until<UTC_TIMESTAMP(6)) ORDER BY next_poll_at,device_id LIMIT :limit").bind("org",org).bind("limit",limit).map((r,m)->decode(r)).all();}
    public Mono<Stored> acquire(Stored expected,boolean scheduled){String token=UUID.randomUUID().toString();return database().sql("UPDATE application_source SET status='RUNNING',last_attempt_at=UTC_TIMESTAMP(6),lease_token=:token,lease_until=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 90 SECOND) WHERE organization_id=:org AND device_id=:device AND revision=:revision AND (lease_until IS NULL OR lease_until<UTC_TIMESTAMP(6))"+(scheduled?" AND enabled=1 AND next_poll_at<=UTC_TIMESTAMP(6)":""))
        .bind("org",expected.organizationId()).bind("device",expected.deviceId()).bind("revision",expected.revision()).bind("token",token).fetch().rowsUpdated().flatMap(n->n==1?get(expected.organizationId(),expected.deviceId()).filter(v->token.equals(v.leaseToken())).switchIfEmpty(Mono.error(ApiException.conflict())):Mono.error(ApiException.conflict()));}
    public Mono<Void> assertLease(Stored v,long credentialRevision){return database().sql("SELECT /*+ MAX_EXECUTION_TIME(3000) */ a.device_id FROM application_source a JOIN device_connection c ON c.organization_id=a.organization_id AND c.device_id=a.device_id AND c.slot='snmp' WHERE a.organization_id=:org AND a.device_id=:device AND a.revision=:revision AND a.lease_token=:token AND a.lease_until>UTC_TIMESTAMP(6) AND c.revision=:credential")
        .bind("org",v.organizationId()).bind("device",v.deviceId()).bind("revision",v.revision()).bind("token",v.leaseToken()).bind("credential",credentialRevision).map((r,m)->true).one().switchIfEmpty(Mono.error(ApiException.conflict())).then();}
    public Mono<Stored> finish(Stored v,Sample sample,long credentialRevision,int rowCount,String code,String message,List<String> flags){
        String success=sample==null?"":",baseline=:baseline,baseline_credential_revision=:credential,last_success_at=UTC_TIMESTAMP(6),last_row_count=:rows,quality_flags=:flags";
        var spec=database().sql("UPDATE application_source SET status=:status,error_code=:code,error_message=:message,lease_token='',lease_until=NULL,next_poll_at=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL :seconds SECOND)"+success+" WHERE organization_id=:org AND device_id=:device AND revision=:revision AND lease_token=:token AND lease_until>UTC_TIMESTAMP(6)"+(sample==null?"":" AND EXISTS(SELECT 1 FROM device_connection c WHERE c.organization_id=:org AND c.device_id=:device AND c.slot='snmp' AND c.revision=:credential)"))
            .bind("status",sample==null?"ERROR":flags.isEmpty()?"SUCCESS":"PARTIAL").bind("code",code).bind("message",message).bind("seconds",v.intervalSeconds()).bind("org",v.organizationId()).bind("device",v.deviceId()).bind("revision",v.revision()).bind("token",v.leaseToken());
        if(sample!=null)spec=spec.bind("baseline",json.writeValueAsString(sample)).bind("credential",credentialRevision).bind("rows",rowCount).bind("flags",json.writeValueAsString(flags));
        return spec.fetch().rowsUpdated().flatMap(n->n==1?get(v.organizationId(),v.deviceId()):Mono.error(ApiException.conflict()));
    }
    public Mono<Void> audit(String org,String actor,String action,String device){return database().sql("INSERT INTO control_audit(organization_id,id,actor,action,resource_id,created_at) VALUES(:org,:id,:actor,:action,:device,UTC_TIMESTAMP(6))").bind("org",org).bind("id",UUID.randomUUID().toString()).bind("actor",actor).bind("action",action).bind("device",device).fetch().rowsUpdated().then();}
}
